"""Create reviews table and columns

Revision ID: 23af01b276a2
Revises: dff473fa2427
Create Date: 2023-12-06 10:57:51.212841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23af01b276a2'
down_revision = 'dff473fa2427'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_reviews_hotel_id_hotels')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    # ### end Alembic commands ###
