"""Add password_hash column to customers table

Revision ID: 949ae6676a31
Revises: df4acd2539f7
Create Date: 2023-12-20 12:17:33.333237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '949ae6676a31'
down_revision = 'df4acd2539f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
